# Generated by Django 4.2.9 on 2024-02-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OHLCModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("csv_file", models.FileField(upload_to="technical_analysis/ohlc")),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ohlc_set", to="core.symbolmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "OHLC",
                "db_table": "technicalanalysis_ohlc",
            },
        ),
    ]
