# Generated by Django 4.2.9 on 2024-02-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUserProfileModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_oid", models.BigIntegerField(db_index=True, unique=True)),
                ("is_default", models.BooleanField(default=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Telegram User Profile",
                "db_table": "telegrambot_telegramuserprofile",
            },
        ),
    ]
