# Generated by Django 4.2.9 on 2024-02-15 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuserprofilemodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegramuserprofile_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramuserprofilemodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="only_one_default_telegram_profile_per_user",
            ),
        ),
    ]
