version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  production_django_logs: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: financipy_production_django
    volumes:
      - production_django_media:/app/financipy/media
      - production_django_logs:/app/financipy/logs
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    command: /start

  telegrampoll:
    <<: *django
    image: financipy_production_telegrampoll
    command: /start-telegrampoll

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: financipy_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: financipy_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: financipy_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: financipy_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: financipy_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    ports:
      - '0.0.0.0:80:80'
