# Generated by Django 4.2.9 on 2024-02-17 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import financipy.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="userprofile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "English"), ("fa", "Persian"), ("ar", "Arabic")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "latest_language",
                    models.CharField(choices=[("en", "English"), ("fa", "Persian"), ("ar", "Arabic")], max_length=3),
                ),
                (
                    "preferred_timezone",
                    models.CharField(max_length=15, validators=[financipy.utils.validators.validate_zoneinfo]),
                ),
                (
                    "preferred_calendar",
                    models.CharField(
                        choices=[("gregorian", "gregorian"), ("solar_hijri", "solar hijri")], max_length=15
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "db_table": "users_userprofile",
            },
        ),
    ]
