# Generated by Django 4.2.9 on 2024-02-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SymbolModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=63, unique=True)),
                (
                    "market",
                    models.CharField(choices=[("tehran_stock_exchange", "Tehran Stock Exchange")], max_length=127),
                ),
            ],
            options={
                "verbose_name": "Symbol",
                "db_table": "core_symbol",
            },
        ),
    ]
