# Generated by Django 4.2.9 on 2024-02-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketWatcherNotifModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_title", models.CharField(max_length=255)),
                ("original_body", models.TextField()),
                ("publish_time", models.DateTimeField()),
                ("ai_body", models.TextField(blank=True, null=True)),
                (
                    "related_market",
                    models.CharField(choices=[("tehran_stock_exchange", "Tehran Stock Exchange")], max_length=127),
                ),
            ],
            options={
                "verbose_name": "Market Watcher Notif",
                "db_table": "fundamentalanalysis_marketwatchernotif",
            },
        ),
        migrations.CreateModel(
            name="MarketWatcherNotifProfileModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("active", "active"), ("inactive", "inactive")])),
                ("ai_boosted", models.BooleanField()),
            ],
            options={
                "verbose_name": "MarketWatcher Notif Profile",
                "db_table": "fundamentalanalysis_marketwatchernotifprofile",
            },
        ),
        migrations.CreateModel(
            name="MarketWatcherNotifSatisfyModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ai_boosted", models.BooleanField()),
                (
                    "notif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketwatchernotifsatisfy_set",
                        to="fundamental_analysis.marketwatchernotifmodel",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketwatchernotifsatisfy_set",
                        to="fundamental_analysis.marketwatchernotifprofilemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Watcher Notif Satisfy",
                "db_table": "fundamentalanalysis__marketwatchernotifsatisfy",
            },
        ),
    ]
