# Generated by Django 4.2.9 on 2024-02-15 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fundamental_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketwatchernotifprofilemodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketwatchernotifprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marketwatchernotifmodel",
            name="related_symbol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketwatchernotif_set",
                to="core.symbolmodel",
            ),
        ),
    ]
